//DRAWER
export const OPEN_SIGN_UP_MODAL = "OPEN_SIGN_UP_MODAL";
export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const OPEN_NEW_REQUEST_MODAL = "OPEN_NEW_REQUEST_MODAL";
export const OPEN_NEW_ITEM_TO_SELL_MODAL = "OPEN_NEW_ITEM_TO_SELL_MODAL";
export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";
export const OPEN_DELETE_MODAL = "OPEN_DELETE_MODAL";

//STARTPAGE
export const OPEN_USERS_ITEMS_MODAL = "OPEN_USERS_ITEMS_MODAL";
export const ITEM_TO_FETCH_USERS = "ITEM_TO_FETCH_USERS";

//Chat
export const SET_SELECTED_PARTICIPANT = "SET_SELECTED_PARTICIPANT";
export const SET_NOTIFICATION = "SET_NOTIFICATION";

//USER
export const SET_USER_NAME = "SET_USER_NAME";

//DASHBOARD
export const SET_ACTIVE_DASHBOARD = "SET_ACTIVE_DASHBOARD";
